# Generated by Django 2.2.5 on 2019-10-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Company Name', max_length=100)),
                ('logo', models.ImageField(upload_to='company')),
                ('address', models.TextField(blank=True, help_text='Company Address', null=True)),
                ('company_type', models.CharField(help_text='Company Type', max_length=250)),
            ],
        ),
    ]
