# Generated by Django 2.2.5 on 2019-10-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20191005_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Developer'), (2, 'Sales Manager'), (3, 'Analyst'), (4, 'Operations'), (5, 'Account Manager')], default='1'),
        ),
    ]
